echo -e "\n========================================"
echo -e "          Welcome to NeOS"
echo -e "========================================"
echo -e "1. To connect to Wi-Fi, type: nmtui"
echo -e "2. To start the installer, type: archinstall"
echo -e "========================================\n"
