# Add 'documentation' label to any changes to .md files or docs/ folder
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'

# Add 'core' label to any changes to root configuration files
core:
  - changed-files:
    - any-glob-to-any-file:
      - 'profiledef.sh'
      - 'pacman.conf'
      - 'packages.*'
      - 'mkinitcpio.conf'

# Add 'ci' label to any changes to .github/ folder
ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'

# Add 'scripts' label to changes in airootfs/usr/local/bin
scripts:
  - changed-files:
    - any-glob-to-any-file:
      - 'airootfs/usr/local/bin/**'
