# Add 'core' label to any changes within 'airootfs' directory
core:
- profile/airootfs/**/*

# Add 'packages' label to changes in package lists
packages:
- profile/packages.*
- profile/bootstrap_packages.*

# Add 'config' label to changes in profiledef.sh or pacman.conf
config:
- profile/profiledef.sh
- profile/pacman.conf

# Add 'boot' label to changes in bootloader configurations
boot:
- profile/syslinux/**/*
- profile/grub/**/*

# Add 'documentation' label to changes in docs or markdown files
documentation:
- docs/**/*
- "*.md"

# Add 'ci' label to changes in .github directory
ci:
- .github/**/*

# Add 'scripts' label to changes in build scripts
scripts:
- build.sh
- tests/**/*
- tools/**/*
