#!/bin/bash
# Drift guard for the generated Calamares netinstall manifests.
#
# tools/gen-manifests.sh is the single source of truth for neos-packages.txt
# and neos-overlay.txt and is run by both build.sh and the CI build job
# before mkarchiso. Because CI always regenerates before building, a stale
# COMMITTED copy never breaks CI — it silently ships ISOs whose installed
# systems miss newer overlay files and packages (CWE-436 configuration
# drift; the exact regression class from the 2026.07.03 and 2026.08.18
# audits, see reports/v2026.09.11/).
#
# This guard regenerates both manifests in an isolated copy of profile/
# and fails if the committed copies differ. The working tree is never
# touched, so the check is safe to run locally on a dirty checkout.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKGS="profile/airootfs/etc/calamares/neos-packages.txt"
OVERLAY="profile/airootfs/etc/calamares/neos-overlay.txt"

FAIL=0

echo "Verifying committed netinstall manifests are in sync with tools/gen-manifests.sh..."

for manifest in "$REPO_ROOT/$PKGS" "$REPO_ROOT/$OVERLAY"; do
    if [[ ! -f "$manifest" ]]; then
        echo "❌ Missing committed manifest: $manifest"
        FAIL=1
    fi
done

if (( FAIL )); then
    echo ""
    echo "Run 'bash tools/gen-manifests.sh' to generate them, then commit the results."
    exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# Regenerate in an isolated copy so the working tree is never modified.
mkdir -p "$WORK_DIR/profile"
cp -a "$REPO_ROOT/profile/packages.x86_64" "$WORK_DIR/profile/packages.x86_64"
cp -a "$REPO_ROOT/profile/airootfs" "$WORK_DIR/profile/airootfs"

if ! bash "$REPO_ROOT/tools/gen-manifests.sh" "$WORK_DIR" >/dev/null; then
    echo "❌ tools/gen-manifests.sh failed in the isolated copy"
    exit 1
fi

echo ""
echo "Verifying manifest format invariants..."
# neos-packages.txt is comment-tolerant (consumers grep out '# ...' lines) and
# must carry the AUTO-GENERATED header to deter hand edits.
if head -n 1 "$REPO_ROOT/$PKGS" | grep -q '^# AUTO-GENERATED by tools/gen-manifests.sh'; then
    echo "✅ $PKGS carries the AUTO-GENERATED header"
else
    echo "❌ $PKGS is missing the AUTO-GENERATED header (hand-edited?)"
    FAIL=1
fi
# neos-overlay.txt is fed verbatim to 'rsync --files-from' by neos-pacstrap,
# which parses every line as a literal filename: no header, no comments, no
# blank lines are tolerable there.
if grep -qE '^\s*(#|$)' "$REPO_ROOT/$OVERLAY"; then
    echo "❌ $OVERLAY contains comment or blank lines (rsync --files-from parses every line as a filename)"
    grep -nE '^\s*(#|$)' "$REPO_ROOT/$OVERLAY" | head -n 5
    FAIL=1
else
    echo "✅ $OVERLAY contains only literal filename lines (rsync --files-from safe)"
fi

echo ""
echo "Diffing committed manifests against regenerated output..."
for manifest in "$PKGS" "$OVERLAY"; do
    # Compare logical content: strip CRs so the check is stable on Windows
    # checkouts (core.autocrlf can hand out CRLF working-tree copies of the
    # LF-indexed manifests; the committed content is LF).
    name="${manifest##*/}"
    tr -d '\r' < "$REPO_ROOT/$manifest" > "$WORK_DIR/committed.$name"
    tr -d '\r' < "$WORK_DIR/$manifest" > "$WORK_DIR/generated.$name"
    if diff -u "$WORK_DIR/committed.$name" "$WORK_DIR/generated.$name" > "$WORK_DIR/diff.patch"; then
        echo "✅ $manifest is in sync"
    else
        echo "❌ $manifest has DRIFTED from tools/gen-manifests.sh output:"
        head -n 40 "$WORK_DIR/diff.patch"
        FAIL=1
    fi
done

if (( FAIL )); then
    echo ""
    echo "Manifest drift detected. Fix with:"
    echo "  bash tools/gen-manifests.sh"
    echo "  git add $PKGS $OVERLAY"
    echo "  git commit"
    exit 1
fi

echo ""
echo "All manifest drift checks passed!"
exit 0
