# bootloader.conf
---
efiBootLoader: "grub"
kernel: "/vmlinuz-linux-lts"
img: "/initramfs-linux-lts.img"
fallback: "/initramfs-linux-lts-fallback.img"
timeout: 5
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
