# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
mountOptions:
    - filesystem: default
      options: [ defaults ]
    - filesystem: btrfs
      options: [ defaults, noatime, compress=zstd:1, discard=async, space_cache=v2 ]
    - filesystem: efi
      options: [ defaults, umask=0077 ]
    - filesystem: btrfs_swap
      options: [ defaults, noatime ]

# btrfs: compress=zstd:1 discard=async space_cache=v2
# Bolt: [Performance] Evaluate fstab.conf Btrfs mount options for I/O throughput.
