# partition.conf
---
efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    512MiB
    minimumSize:        256MiB
    label:              "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType:  "btrfs"
availableFileSystemTypes: ["btrfs", "ext4", "xfs"]
