# shellprocess.conf - Post-install cleanup
---
dontChroot: false
timeout: 300
script:
    - command: "rm -f /etc/sudoers.d/zz-live-wheel"
    - command: "rm -f /etc/systemd/system/getty@tty1.service.d/autologin.conf"
    - command: "rmdir --ignore-fail-on-non-empty /etc/systemd/system/getty@tty1.service.d 2>/dev/null || true"
    - command: "rm -f /etc/sddm.conf.d/autologin.conf"
    - command: "rm -f /etc/sddm.conf.d/00-allow-empty-password.conf"
    - command: "rm -f /etc/skel/Desktop/welcome-neos.desktop"
    - command: "rm -f /home/*/Desktop/welcome-neos.desktop"
    - command: "rm -f /etc/xdg/autostart/neos-welcome-app.desktop"
    - command: "rm -f /usr/local/bin/neos-welcome-app"
    - command: "rm -f /usr/local/bin/neos-welcome"
    - command: "rm -f /usr/local/bin/neos-liveuser-setup"
    - command: "rm -f /etc/skel/.config/autostart/neos-desktop-setup.desktop"
    - command: "rm -f /etc/systemd/system/neos-liveuser-setup.service"
    - command: "rm -f /etc/systemd/system/systemd-firstboot.service"
    - command: "rm -rf /etc/calamares"
    - command: "locale-gen"
    - command: "pacman-key --init"
    - command: "pacman-key --populate archlinux"
    - command: "pacman-key --populate chaotic"
    - command: "systemctl enable NetworkManager"
    - command: "systemctl enable bluetooth"
    - command: "systemctl enable sddm"
