# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
defaultGroups: []

sudoersGroup: wheel
setRootPassword: false
doReusePassword: false
displayAutologin: true
doAutologin: false

user:
  shell: /bin/bash
  forbidden_names: [ root ]

hostname:
  location: EtcFile
  writeHostsFile: true
# Sentinel: [Security] Audit user group assignments in users.conf to ensure principle of least privilege.
