# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
defaultGroups:
    - name: wheel
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: audio
      must_exist: false
      system: true
    - name: storage
      must_exist: false
      system: true
    - name: power
      must_exist: false
      system: true
    - name: network
      must_exist: false
      system: true
    - name: lp
      must_exist: false
      system: true
    - name: input
      must_exist: false
      system: true

sudoersGroup: wheel
setRootPassword: false
doReusePassword: false
displayAutologin: true
doAutologin: false

user:
  shell: /bin/zsh
  forbidden_names: [ root ]

hostname:
  location: EtcFile
  writeHostsFile: true
