# welcome.conf
---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

geoip:
    style: "json"
    url: "https://ipapi.co/json"
    selector: "country_name"

requirements:
    requiredStorage:    20.0
    requiredRam:        2.0
    internetCheckUrl:   https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
        - screen
