# NeOS Calamares Settings
---
modules-search: [ local ]

instances:
- id:       cleanup
  module:   shellprocess
  config:   shellprocess.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - shellprocess@cleanup
  - umount
- show:
  - finished

branding: neos
prompt-install: true
dont-chroot: false
compact-labels: true
show-back-button: true
show-cancel-button: true
