# NeOS Calamares Settings
---
modules-search: [ local ]

instances:
- id:       pacstrap
  module:   shellprocess
  config:   pacstrap.conf
- id:       cleanup
  module:   shellprocess
  config:   shellprocess.conf
- id:       unmountprep
  module:   shellprocess
  config:   unmount-prep.conf
- id:       liveuser
  module:   shellprocess
  config:   liveuser-setup.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - summary
- exec:
  - partition
  - mount
  - shellprocess@pacstrap
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initcpiocfg
  - initcpio
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - shellprocess@liveuser
  - grubcfg
  - bootloader
  - shellprocess@cleanup
  - shellprocess@unmountprep
  - umount
- show:
  - finished

branding: neos
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
