#!/bin/bash
# NeOS netinstall manifest generator — single source of truth for build.sh and
# the CI workflow. MUST run before mkarchiso: Calamares reads both manifests
# from the ISO, and a stale committed copy means installed systems silently
# miss newer overlay files or packages.
#
# Generates:
#   profile/airootfs/etc/calamares/neos-packages.txt  (pacstrap package list)
#   profile/airootfs/etc/calamares/neos-overlay.txt   (overlay copy manifest)
#
# Usage: gen-manifests.sh [REPO_ROOT]

set -euo pipefail

# Sentinel: [Security] Enforce strict PATH to prevent path hijacking
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

REPO_ROOT="${1:-$PWD}"
PROFILE_DIR="$REPO_ROOT/profile"

# Generate the netinstall package list that Calamares pacstraps into the
# target. It is derived from the live ISO package list (single source of
# truth) minus packages that only make sense on the live medium itself:
#   - mkinitcpio-archiso : live-boot initramfs hooks, not for an installed disk
#   - calamares-garuda   : the installer, has no place on the installed system
NETINSTALL_PKGS="$PROFILE_DIR/airootfs/etc/calamares/neos-packages.txt"
echo "Generating netinstall package list -> $NETINSTALL_PKGS"
{
    echo "# AUTO-GENERATED by tools/gen-manifests.sh from profile/packages.x86_64 — do not edit."
    echo "# Packages pacstrapped onto the target by the Calamares 'pacstrap' step."
    grep -vE '^\s*(#|$)' "$PROFILE_DIR/packages.x86_64" \
        | grep -vxE 'mkinitcpio-archiso|calamares-garuda'
    # Developer toolchains — INSTALLED-SYSTEM ONLY (deliberately NOT in the
    # size-gated live ISO's packages.x86_64): modern languages so a fresh NeOS
    # install is dev-ready out of the box. three.js is an npm library, not a
    # system package — `npm install three` once nodejs/npm are present.
    echo "# --- developer languages and frameworks (installed-system only) ---"
    printf '%s\n' \
        nodejs npm python-pip rust go deno base-devel \
        jdk-openjdk ruby php composer dotnet-sdk \
        clang cmake ninja gdb docker docker-compose \
        zig nim bun gleam elixir odin crystal

    echo "# --- heavy desktop applications and drivers (installed-system only) ---"
    printf '%s\n' \
        firefox discover packagekit-qt6 cups print-manager \
        fwupd flatpak noto-fonts-cjk nvidia-dkms dkms \
        linux-lts-headers broadcom-wl-dkms
} > "$NETINSTALL_PKGS"

# Generate the NeOS overlay manifest that Calamares copies onto the target
# after pacstrap. A pacstrap install only lays down packages, so without this
# the installed system would be vanilla Arch with none of NeOS's branding,
# custom services or hardening (all of which live in the airootfs overlay, not
# in packages). The manifest lists every overlay file EXCEPT the live-/
# installer-only ones that must never reach an installed disk.
NETINSTALL_OVERLAY="$PROFILE_DIR/airootfs/etc/calamares/neos-overlay.txt"
echo "Generating NeOS overlay manifest -> $NETINSTALL_OVERLAY"
(
    cd "$PROFILE_DIR/airootfs" && find . \( -type f -o -type l \) -printf '%P\n'
) | grep -vE \
    -e '^etc/calamares/' \
    -e '^etc/pacman\.conf$' \
    -e '^etc/pacman\.d/' \
    -e '^etc/polkit-1/rules\.d/49-nopasswd_calamares\.rules$' \
    -e '^etc/machine-id$' \
    -e '^etc/hostname$' \
    -e '^etc/locale\.conf$' \
    -e '^etc/locale\.gen$' \
    -e '^etc/mkinitcpio\.conf$' \
    -e '^etc/mkinitcpio\.d/' \
    -e '^root/' \
    -e '^etc/systemd/system/pacman-init\.service$' \
    -e '^etc/systemd/system/etc-pacman\.d-gnupg\.mount$' \
    -e '^etc/sudoers\.d/zz-live-wheel$' \
    -e '^etc/systemd/system/[^/]+\.target\.wants/' \
    -e '^etc/systemd/system/getty@tty1\.service\.d/' \
    -e '^etc/systemd/system/display-manager\.service$' \
    -e '^etc/systemd/system/neos-liveuser-setup\.service$' \
    -e '^etc/systemd/system/systemd-firstboot\.service$' \
    -e '^etc/sddm\.conf\.d/autologin\.conf$' \
    -e '^etc/sddm\.conf\.d/00-allow-empty-password\.conf$' \
    -e '^usr/local/bin/neos-liveuser-setup$' \
    -e '^usr/local/bin/neos-welcome$' \
    -e '^usr/local/bin/neos-welcome-app$' \
    -e '^usr/local/bin/neos-pacstrap$' \
    -e '^etc/skel/Desktop/welcome-neos\.desktop$' \
    -e '^etc/xdg/autostart/neos-welcome-app\.desktop$' \
    -e '^etc/skel/\.config/autostart/neos-desktop-setup\.desktop$' \
    | sort > "$NETINSTALL_OVERLAY"

echo "Generated $(wc -l < "$NETINSTALL_OVERLAY") overlay entries"
